server:
  port: 8080

spring:
  application:
    name: etrade
  
  
  datasource:
    #    url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./db/etrade
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false #prevent trace from being written to the console
        web-allow-others: false # for security reasons, disable remote access


logging:
  level:
    root: info
    org.springframework: error
    springframework.security: off
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet.DispatcherServlet: ERROR
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: ERROR
    org.springframework.orm.jpa.OpenEntityManagerInViewInterceptor: ERROR

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true